dating_main_homepage:
    path:     /
    defaults: { _controller: DatingMainBundle:Default:index }

dating_main_profile:
    resource: "@DatingMainBundle/Resources/config/routing/profile.yml"
    prefix:     /profile

