dating_admin:
    resource: "@DatingAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

dating_main:
    resource: "@DatingMainBundle/Resources/config/routing.yml"
    prefix:   /

dating_user:
    resource: "@DatingUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
