dating_user_homepage:
    path:     /
    defaults: { _controller: DatingUserBundle:Default:index }

user_login:
    pattern:   /login
    defaults: { _controller: DatingUserBundle:Security:login }

user_login_check:
    pattern:   /login_check

user_logout:
    pattern:  /logout

user_register:
    pattern:  /register
    defaults: { _controller: DatingUserBundle:Registration:register }

user_checkEmail:
    pattern:  /check-email

user_confirm:
    pattern:  /confirm/{token}

user_confirmed:
    pattern:  /confirmed
    defaults: { _controller: DatingUserBundle:Registration:confirmed }