dating_user_security:
    resource: "@DatingUserBundle/Resources/config/routing/security.yml"
    prefix:   /

dating_user_homepage:
    path:     /
    defaults: { _controller: DatingUserBundle:Default:index }

user_register:
    pattern:  /register
    defaults: { _controller: DatingUserBundle:Registration:register }

user_checkEmail:
    pattern:  /check-email

user_confirm:
    pattern:  /confirm/{token}

user_confirmed:
    pattern:  /confirmed
    defaults: { _controller: DatingUserBundle:Registration:confirmed }

user_profile:
    pattern: /profile
    defaults: { _controller: DatingUserBundle:Profile:show }

user_profile_edit:
    pattern: /profile/edit
    defaults: { _controller: DatingUserBundle:Profile:edit }

