Dating\UserBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        profile:
            targetEntity: Dating\AdminBundle\Entity\Profile
            mappedBy: createdBy
            nullable: true
    lifecycleCallbacks: {  }
