Dating\UserBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        profile:
            targetEntity: Dating\AdminBundle\Entity\Profile
            mappedBy: createdBy
            nullable: true
    manyToMany:
        likes:
            targetEntity: Dating\UserBundle\Entity\User
            mappedBy: myLikes
        myLikes:
            targetEntity: Dating\UserBundle\Entity\User
            inversedBy: likes
            joinTable:
                name: myLikes
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    like_user_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
