dating_admin_survey:
    resource: "@DatingAdminBundle/Resources/config/routing/survey.yml"
    prefix:   /survey

dating_admin_profile:
    resource: "@DatingAdminBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

dating_admin_homepage:
    path:     /
    defaults: { _controller: DatingAdminBundle:Default:index }
